### PR TITLE
refactor: fix shellcheck warnings

### PR DESCRIPTION
**Pull request by jgiovaresco**

### CODE REVIEW

**Comment by graviteeio** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/gravitee-io/keeper?version=dev:486620f78efd57fe6a15d1125a79512626f6f778

**Comment by graviteeio** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/gravitee-io/keeper?version=dev:da431450a0513a12cc118b21a17cf8728462cc2f

**Comment by graviteeio** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/gravitee-io/keeper?version=dev:5db87c6f2be732ad1a9ad60cff60a82cc92e644f

**Review by gaetanmaisse — APPROVED** [review]

**Comment by graviteeio** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/gravitee-io/keeper?version=dev:9e5ef6dd595e940a0b33aeaa8bc2a055d22d0a1b

**Comment by graviteeio** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/gravitee-io/keeper?version=dev:9e5ef6dd595e940a0b33aeaa8bc2a055d22d0a1b

**Comment by graviteeio** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/gravitee-io/keeper?version=0.6.3

**Pull request merged**
